-- MySQL Script generated by MySQL Workbench
-- Sun Mar 26 01:13:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`preRegistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`preRegistro` (
  `cpf` VARCHAR(14) NOT NULL,
  `coordenador` BIT(1) NOT NULL,
  `professor` BIT(1) NOT NULL,
  `orientador` BIT(1) NOT NULL,
  `aluno` BIT(1) NOT NULL,
  `ano` INT NULL,
  `semestre` INT NULL,
  `cadastrado` BIT(1) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(64) NOT NULL,
  `coordenador` BIT(1) NOT NULL,
  `professor` BIT(1) NOT NULL,
  `orientador` BIT(1) NOT NULL,
  `aluno` BIT(1) NOT NULL,
  `ano` INT NULL,
  `semestre` INT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_preRegistro_idx` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_preRegistro`
    FOREIGN KEY (`cpf`)
    REFERENCES `database`.`preRegistro` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`orientacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`orientacoes` (
  `idOrientacoes` INT NOT NULL AUTO_INCREMENT,
  `idAlunoOrientado` INT NOT NULL,
  `idProfessorOrientador` INT NOT NULL,
  `StatusAprovacao` CHAR(1) NOT NULL,
  PRIMARY KEY (`idOrientacoes`),
  INDEX `fk_orientacoes_usuarios1_idx` (`idAlunoOrientado` ASC) VISIBLE,
  INDEX `fk_orientacoes_usuarios2_idx` (`idProfessorOrientador` ASC) VISIBLE,
  CONSTRAINT `fk_orientacoes_usuarios1`
    FOREIGN KEY (`idAlunoOrientado`)
    REFERENCES `database`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orientacoes_usuarios2`
    FOREIGN KEY (`idProfessorOrientador`)
    REFERENCES `database`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
